config/routes.rb
RobinsonFarms::Application.routes.draw do

  devise_for :users
  get 'general_pages/admin' => 'general_pages#admin', as: :admin
  get 'subcategories/show_all' => 'subcategories#show_all', as: :show_all

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :list_items
  end

  resources :general_pages

  resources :list_items

   root 'general_pages#home'

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
	belongs_to :category
	has_many :list_items

	mount_uploader :main_image, ImageUploader
	mount_uploader :banner_image, ImageUploader
	mount_uploader :content_image, ImageUploader
	mount_uploader :bottom_divider_image, ImageUploader
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: [:show, :show_all, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
    @li = ListItem.where(:subcategory_id => @subcategory.id)
    @haylage = Subcategory.where(:name => 'Haylage').first
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
  end

  # GET /subcategories/1/edit
  def edit
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @subcategory }
      else
        format.html { render action: 'new' }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :category_id, :page_title, :page_description, :content_title, 
        :content_description, :optional_information, :main_image, :banner_image, :content_image, :home_page_content,
        :link_one, :link_two, :banner_link_text, :bottom_divider_image)
    end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= render 'layouts/admin_menu' %>

<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field('category_id', :value => params[:category_id]) %>

  <div class="admin-form-heading">
    <p>Choose Category</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
     <%= f.label :category_id %>
   </div>
   <div class="col span-input admin-field">
      <%= f.collection_select :category_id, Category.order(:name), :id, :name, :include_blank=>false %>
    </div>
  </div>

  <div class="admin-form-heading">
    <p>Subcategory Details</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :name %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :page_title %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :page_title %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :page_description %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :page_description, :class => 'tinymce', :rows => 10, :cols => 120 %>
      <%= tinymce %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :content_title %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :content_title %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :content_description %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :content_description, :class => 'tinymce', :rows => 10, :cols => 120 %>
      <%= tinymce %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :optional_information %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :optional_information, :class => 'tinymce', :rows => 10, :cols => 120 %>
      <%= tinymce %>
    </div>
  </div> 

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :banner_link_text %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :banner_link_text %>
    </div>
  </div>   

  <div class="admin-form-heading">
    <p>Home Page Content</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :home_page_content %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :home_page_content, :class => 'tinymce', :rows => 10, :cols => 120 %>
      <%= tinymce %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :link_one, 'First Link Text (optional)' %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :link_one %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :link_two, 'Second Link Text (optional)' %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :link_two %>
    </div>
  </div>

  <div class="admin-form-heading">
    <p>Image(s)</p>
  </div>  

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :main_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :main_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :banner_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :banner_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :bottom_divider_image %>
    </div>
    <div lass="col span-input admin-field">
      <%= f.file_field :bottom_divider_image %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Save", :class => "button button-new" %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<div class="section group heading heading-desktop heading-admin">
	Edit subcategory
</div>

<%= render 'form' %>

app/views/subcategories/index.html.erb
<%= render 'layouts/admin_menu' %>

<div class="heading heading-desktop heading-admin">
  Listing subcategories
</div>

<table class="admin-table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Main Category</th>
      <th>Page Desc.</th>
      <th>Content Desc.</th>
      <th>Banner Image</th>
      <th>Main Image</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.category.name %></td>
        <td><%= subcategory.page_description.html_safe unless subcategory.page_description.nil? %></td>
        <td><%= subcategory.content_description.html_safe unless subcategory.content_description.nil? %></td>
        <td><%= image_tag subcategory.banner_image_url(:thumbnail).to_s %></td>
        <td><%= image_tag subcategory.main_image_url(:thumbnail).to_s %></td>
        <td>
          <%= link_to 'Show', subcategory %><br />
          <%= link_to 'Edit', edit_subcategory_path(subcategory) %><br />
          <%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path, :class => "button button-new" %>

app/views/subcategories/new.html.erb
<div class="section group heading heading-desktop heading-admin">
	New subcategory
</div>

<%= render 'form' %>

app/views/subcategories/show.html.erb
<%= render 'layouts/menu_mobile' %>

<div class="menu">
	<%= render 'layouts/menu_desktop' %>
</div>

<div class="page-title page-title-brown page-title-phone subcat-title-phone">
	<div class="col-full-row">
		<%= @subcategory.page_title %>
	</div>
</div>

<!-- page header  -->
<div class="section group banner-desktop">
	<div class="col-full-row">
		<%= image_tag @subcategory.banner_image_url.to_s %>
	</div>
</div>

<div class="section group banner-mobile">
	<div class="col-full-row">
		<%= image_tag @subcategory.banner_image_url.to_s %>
	</div>
</div>

<div class="section-on-top page-title page-title-brown hidden-mobile">
	<div class="col span-3-of-3">
		<%= @subcategory.page_title %>
	</div>
</div>


<div class="section group page-description">

	<div class="col span-1-of-3 page-desc-text page-desc-subcat">
		<%= @subcategory.page_description.html_safe unless @subcategory.page_description.nil? %>
	</div>

	<% if !(@subcategory.banner_link_text.eql? "")  %>
		<div class="button button-grey subcat-desc-button">
			<%= link_to @subcategory.banner_link_text %>
		</div>
	<% end %>

</div>

<%= render 'layouts/social_feed_top' %>

<!-- content headings and banner in desktop -->
<div class="section group hidden-mobile">

	<div class="col-full-row banner-desktop">
		<%= image_tag @subcategory.main_image_url.to_s %>
	</div>

	<% if !(@subcategory.content_title.eql? "") %>
		<% if @subcategory.name.eql? "Meet The Robinsons" %>
			<div class="section-on-top content-title meet-rob-content-title">
				<p><%= @subcategory.content_title %></p>
			</div>
		<% else %>
			<div class="section-on-top content-title subcat-content-title">
				<p><%= @subcategory.content_title %></p>
			</div>
		<% end %>	
	<% end %>	

</div>

<!-- content in phone -->

<div class="section group main-image hidden-desktop">
	<div class="col-full-row">
		<%= image_tag @subcategory.main_image_url.to_s %>
	</div>
</div>

<div class="section group hidden-desktop">
	<div class="coll-full-row content-title subcat-content-title">
		<p><%= @subcategory.content_title %></p>
	</div>
</div>

<!-- list items desktop -->
<div class="subcat-area hidden-mobile">
	<% if @subcategory.name.eql? "Meet The Robinsons" %>

		<% @li.each do |li| %>

			<div class="section group item-listing">

				<div class="col span-3-of-3 item-image rob-item-image">
					<%= image_tag li.item_image_url.to_s %>
				</div>

				<div class="col span-2-of-3 section-on-top rob-item-details">
					<h4><%= li.name %></h4>
					<div class="rob-quote">
						<%= li.description.html_safe unless li.description.nil? %>
					</div>
					<div class="rob-profile-optional-info">
						<%= li.optional_information.html_safe unless li.optional_information.nil? %>
					</div>
				</div>

				<% if !(li.link_text.eql? "") %>
					<div class="section-on-top button button-brown rob-list-item-button">
						<%= link_to li.link_text, subcategory_path(@haylage) %>
					</div>
				<% end %>

			</div>

		<% end %>

	<% else %>

		<% @li.each do |li| %>

			<div class="section group item-listing">

				<div class="col span-3-of-3 item-image subcat-item-image">
					<%= image_tag li.item_image_url.to_s %>
				</div>

				<div class="col span-2-of-3 section-on-top item-details subcat-item-details">
					<h4><%= li.name %></h4>
					<p><%= li.description.html_safe unless li.description.nil? %></p>
				</div>

				<div class="section-on-top button button-brown list-item-button subcat-list-item-button">
					<%= link_to li.link_text %>
				</div>

			</div>

		<% end %>

	<% end %>

	<div class="col-full-row">
		<%= image_tag @subcategory.bottom_divider_image_url.to_s %>
	</div>	
</div>

<!-- list items mobile -->
<div class="subcat-area subcat-area-mobile">
	<% @li.each do |li| %>
		<div class="section group item-title-mobile">
			<div class="col-full-row">
				<%= li.name %>
			</div>
		</div>
 
		<div class="section group item-image-mobile">
			<div class="col-full-row">
				<%= image_tag li.item_image_url.to_s %>
			</div>
		</div>

		<div class="section group item-description-mobile">
			<div class="col-full-row">
				<%= li.description.html_safe unless li.description.nil? %>
			</div>
		</div>

		<div class="section group item-optional-info-mobile">
			<div class="col-full-row">
				<%= li.optional_information.html_safe unless li.optional_information.nil? %>
			</div>
		</div>

		<% if !(li.link_text.eql? "") %>
			<div class="section group button-brown link-text-mobile">
				<div class="col-full-row">
					<%= link_to li.link_text %>
				</div>
			</div>
		<% end %>
	<% end %>	
</div>

<div class="col-full-row subcat-divider-image hidden-desktop">
	<%= image_tag @subcategory.bottom_divider_image_url.to_s %>
</div>	


<div class="placeholders">
	<div class="map-placeholder">
		<%= image_tag "map.jpg", :id => "map" %>
	</div>
</div>