config/routes.rb
RobinsonFarms::Application.routes.draw do

  devise_for :users
  get 'general_pages/admin' => 'general_pages#admin', as: :admin
  get 'subcategories/show_all' => 'subcategories#show_all', as: :show_all

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :list_items
  end

  resources :general_pages

  resources :list_items

   root 'general_pages#home'

end

app/models/general_page.rb
class GeneralPage < ActiveRecord::Base
	mount_uploader :home_page_banner, ImageUploader
	mount_uploader :home_mobile_banner, ImageUploader
	mount_uploader :menu_image, ImageUploader
	mount_uploader :phone_image, ImageUploader
	mount_uploader :products_home_page_top_image, ImageUploader
	mount_uploader :haylage_home_banner, ImageUploader
	mount_uploader :haylage_inset_image, ImageUploader
	mount_uploader :equipment_home_banner, ImageUploader
	mount_uploader :equipment_inset_image, ImageUploader
	mount_uploader :clients_logo_images, ImageUploader
	mount_uploader :client_image_left, ImageUploader
	mount_uploader :client_image_middle, ImageUploader
	mount_uploader :client_image_right, ImageUploader
	mount_uploader :clients_divider_image, ImageUploader
end

app/controllers/general_pages_controller.rb
class GeneralPagesController < ApplicationController
  before_action :set_general_page, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :home]

  # GET /general_pages
  # GET /general_pages.json
  def index
    @general_pages = GeneralPage.all
  end

  def admin    
  end

  def home
    @general_page = GeneralPage.first 
    @about = Category.where(:name => 'About Us').first
    @product = Category.where(:name => 'Our Products').first
    @haylage = Subcategory.where(:name => 'Haylage').first
    @haylage_products = ListItem.where(:subcategory_id => @haylage.id).first(3)
    @equipment = Subcategory.where(:name => 'Equipment').first
    @client = Subcategory.where(:name => 'Our Clients').first
  end

  # GET /general_pages/1
  # GET /general_pages/1.json
  def show
  end

  # GET /general_pages/new
  def new
    @general_page = GeneralPage.new
  end

  # GET /general_pages/1/edit
  def edit
  end

  # POST /general_pages
  # POST /general_pages.json
  def create
    @general_page = GeneralPage.new(general_page_params)

    respond_to do |format|
      if @general_page.save
        format.html { redirect_to root_url, notice: 'General page was successfully created.' }
        format.json { render action: 'show', status: :created, location: @general_page }
      else
        format.html { render action: 'new' }
        format.json { render json: @general_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /general_pages/1
  # PATCH/PUT /general_pages/1.json
  def update
    respond_to do |format|
      if @general_page.update(general_page_params)
        format.html { redirect_to root_url, notice: 'General page was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @general_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /general_pages/1
  # DELETE /general_pages/1.json
  def destroy
    @general_page.destroy
    respond_to do |format|
      format.html { redirect_to general_pages_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_general_page
      @general_page = GeneralPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def general_page_params
      params.require(:general_page).permit(:name, :home_page_banner, :menu_image, :phone_image, :phone_number, 
        :home_page_title, :home_page_description, :home_mobile_banner, :products_home_page_top_image, 
        :haylage_home_banner, :haylage_inset_image, :equipment_home_banner, :equipment_inset_image, :clients_logo_images,
        :client_image_left, :client_image_middle, :client_image_right, :haylage_content, :haylage_header, :equipment_content,
        :quote, :haylage_link_one, :haylage_link_two, :equipment_link, :clients_link, :clients_divider_image,
        :subcategory_divider_image)
    end
end

app/helpers/general_pages_helper.rb
module GeneralPagesHelper
end

app/views/general_pages/_form.html.erb
<%= render 'layouts/admin_menu' %>

<%= form_for(@general_page) do |f| %>
  <% if @general_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@general_page.errors.count, "error") %> prohibited this general_page from being saved:</h2>

      <ul>
      <% @general_page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="admin-form-heading">
    <p>Home Page Images</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :home_page_banner %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :home_page_banner %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :products_home_page_top_image, 'Products Banner (Home Page)' %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :products_home_page_top_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :haylage_home_banner, 'Haylage Banner (Home Page)' %>
    </div>
    <div class="col span-input admin-field"> 
      <%= f.file_field :haylage_home_banner %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :haylage_inset_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :haylage_inset_image %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :equipment_home_banner %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :equipment_home_banner %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :equipment_inset_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :equipment_inset_image %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :clients_logo_images %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :clients_logo_images %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :client_image_left %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :client_image_left %>
    </div>    
  </div> 

  <div class="section group">
      <div class="col span-label admin-label">
        <%= f.label :client_image_middle %>
      </div>
      <div class="col span-input admin-field">
        <%= f.file_field :client_image_middle %>
      </div>
  </div> 

  <div class="section group">
      <div class="col span-label admin-label">
        <%= f.label :client_image_right %>
      </div>
      <div class="col span-input admin-field">
        <%= f.file_field :client_image_right %>
      </div>
  </div>

  <div class="section group">
      <div class="col span-label admin-label">
        <%= f.label :clients_divider_image %>
      </div>
      <div class="col span-input admin-field">
        <%= f.file_field :clients_divider_image %>
      </div> 
  </div>

  <div class="admin-form-heading">
    <p>Home Page Content</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :home_page_title %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :home_page_title %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :home_page_description %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :home_page_description, :class => 'tinymce', :rows => 10, :cols => 120 %>
      <%= tinymce %>      
    </div>
  </div>

  <div class="section group">
      <div class="col span-label admin-label">
        <%= f.label :quote %>
      </div>
      <div class="col span-input admin-field">
        <%= f.text_area :quote, :class => 'tinymce', :rows => 10, :cols => 60 %>
        <%= tinymce %>
      </div>
  </div>

  <div class="section group">
      <div class="col span-label admin-label">
        <%= f.label :haylage_link_one %>
      </div>
      <div class="col span-input admin-field">
        <%= f.text_field :haylage_link_one %>
      </div>    
  </div>  

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :haylage_link_two %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :haylage_link_two %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :equipment_link %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :equipment_link %>
    </div>    
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :clients_link %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :clients_link %>
    </div>    
  </div>
      
  <div class="admin-form-heading">
    <p>Menu</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :menu_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :menu_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :phone_image %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :phone_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :phone_number %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :phone_number %>
    </div>
  </div>
 

  <div class="actions">
    <%= f.submit "Save", :class => "button button-new" %>
  </div>
<% end %>

app/views/general_pages/admin.html.erb
<%= render 'layouts/admin_menu' %>

<div class="section group heading heading-desktop heading-admin">
	Admin Area
</div>
 
<div class="admin-links">
	<%= link_to "General Settings", general_pages_url %>
</div>

<div class="admin-notes">
	<p>
		Here you can modify a range of settings including home page content.
	</p>
</div>

<div class="admin-links">
	<%= link_to "Categories", categories_url %>
</div>

<div class="admin-notes">
	<p>
		Manage all categories, for eg. About Us, Products etc, here
	</p>
</div>

<div class="admin-links">
	<%= link_to "Subcategories", subcategories_url %>
</div>

<div class="admin-notes">
	<p>
		This is where you can manage/modify subcategories - eg: Meet the Robinsons, Equipment etc.
	</p>
</div>

<div class="admin-links">
	<%= link_to "Subcategory Content", list_items_url %>
</div>

<div class="admin-notes">
	<p>
		Individual client/product/profile contents can be maintainted here
	</p>
</div>

app/views/general_pages/edit.html.erb
<div class="heading heading-desktop heading-admin">
	Edit General Content
</div>

<%= render 'form' %>

app/views/general_pages/home.html.erb
<%= render 'layouts/menu_mobile' %>

<div class="menu">
	<%= render 'layouts/menu_desktop' %>
</div>

<!-- page description in mobile -->
<div class="section group page-title page-title-brown page-title-phone">
	<div class="col-full-row">
		<%= @general_page.home_page_title %>
	</div>
</div>

<!-- Banner images in desktop and mobile -->
<div class="section group banner-desktop">
	<div class="col-full-row">
		<%= image_tag @general_page.home_page_banner_url.to_s %>
	</div>
</div>

<div class="section group banner-mobile">
	<div class="col-full-row">
		<%= image_tag @general_page.home_page_banner_url.to_s %>
	</div>
</div>

<!-- home page description and title  -->
<div class="section-on-top page-title page-title-brown hidden-mobile">
	<div class="col span-3-of-3">
		<%= @general_page.home_page_title %>
	</div>
</div>

<div class="section group page-description">

	<div class="col span-1-of-3 page-desc-text page-desc-home">
		<%= @general_page.home_page_description.html_safe unless @general_page.home_page_description.nil? %>
	</div>

	<div class="section-on-top button button-grey home-page-desc-button">
		<a href="#">The benefits of Haylage</a>
	</div>

</div>

<%= render 'layouts/social_feed_top' %>

<!-- About Us Section -->
<div class="information-area section group">

	<%= image_tag @about.main_image.url(:desktop).to_s  %>

	<div class="section-on-top content-area content-area-brown home-about-content">
		<%= @about.home_page_content.html_safe unless @about.home_page_content.nil? %>
	</div>

	<div class="section-on-top button button-brown about-home-button">
		<%= @about.link_to_subcategory %>
	</div>

</div>

<!-- Products Section -->
<div id= "products" class="information-area section group home-products">

	<%= image_tag @general_page.products_home_page_top_image.url(:desktop).to_s %>

	<div class="section-on-top subcat-page-title subcat-page-title-brown home-products-title">
		<%= @product.name %>
	</div>

	<div class="section-on-top subcat-page-title subcat-page-title-brown home-products-sub-title">
		<%= @product.page_title %>
	</div>

	<div class="section-on-top home-products-content">
		<%= @product.page_description.html_safe unless @product.page_description.nil? %>
	</div>

</div>

<!-- Haylage Section -->

<div class="information-area section group home-haylage">

	<%= image_tag @general_page.haylage_home_banner_url.to_s %>

	<div class="section-on-top haylage-inset-image">
		<%= image_tag @general_page.haylage_inset_image_url.to_s %>
	</div>

	<div class="section-on-top home-haylage-content content-area content-area-green">
		<%= @haylage.home_page_content.html_safe unless @haylage.home_page_content.nil? %>
	</div>

</div>

<!-- Products listing section -->
<div class="information-area section group home-products-listing">

	<% @haylage_products.each do |prod| %>
		<div class="col span-3 home-prod-listing">
			<p><%= prod.name %></p>
			<%= image_tag prod.home_page_image_url.to_s %>
		</div>
	<% end %>

</div>

<!-- product links -->
<div class="section group home-products-links">
	<div class="col span-3 button button-green first-prod-link">
		<%= link_to @haylage.link_one, subcategory_path(@haylage) %>
	</div>
	<div class="col span-3 button button-green second-prod-link">
		<%= link_to @haylage.link_two, subcategory_path(@haylage) %>
	</div>
</div>


<!-- Equipment listing -->
<div class="information-area section group home-equipment">

	<%= image_tag @general_page.equipment_home_banner_url.to_s %>

	<div class="home-equipment-content">
		<%= @equipment.home_page_content.html_safe unless @equipment.home_page_content.nil? %>
	</div>

	<div class="section-on-top button button-brown equip-home-button hidden-mobile">
		<% equip = Subcategory.where(:name=>"Equipment").first %>
		<%= link_to @general_page.equipment_link, subcategory_path(equip) %>
	</div>

</div>

<div class="section group hidden-mobile">
	<div class="col-full-row equip-clients-divider">
		<%= image_tag @general_page.clients_divider_image_url.to_s %>
	</div>
</div>

<!-- Clients Area Desktop
<div class="information-area section group home-clients">
	<div class="side-title side-title-brown">
		<%#= @client.name %>
	</div>
	<div class="client-images logo-images">
		<%#= image_tag @general_page.clients_logo_images_url.to_s %>
	</div>
	<div class="client-images client-image-left">
		<%#= image_tag @general_page.client_image_left_url.to_s %>
	</div>
	<div class="home-client-quote">
		<%#= @general_page.quote.html_safe unless @general_page.quote.nil? %>
	</div>
</div>-->

<div class="placeholders">
	<div class="client-placeholder hidden-mobile">
		<%= image_tag "clients.jpg" %>
	</div>
	<div class="client-placeholder hidden-desktop">
		<%= image_tag "clients-mobile.jpg" %>
	</div>
	<div class="social-placeholder hidden-mobile">
		<%= image_tag "social.jpg" %>
	</div>
	<div class="map-placeholder hidden-mobile">
		<%= image_tag "map.jpg" %>
	</div>	
</div>

app/views/general_pages/index.html.erb
<%= render 'layouts/admin_menu' %>

<div class="heading heading-desktop heading-admin">
  Manage General Settings
</div>

<table class="admin-table">
  <thead>
    <tr>
      <th>Home Page Banner</th>
      <th>Menu Image</th>
      <th>Phone Image</th>
      <th>Phone Number</th>
      <th>Products Top Image</th>
      <th>Haylage Home Page Banner</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @general_pages.each do |general_page| %>
      <tr>
        <td><%= image_tag general_page.home_page_banner_url(:thumbnail).to_s %></td>
        <td><%= image_tag general_page.menu_image_url(:thumbnail).to_s %></td>
        <td><%= image_tag general_page.phone_image_url.to_s %></td>
        <td><%= general_page.phone_number %></td>
        <td><%= image_tag general_page.products_home_page_top_image_url(:thumbnail).to_s %></td>
        <td><%= image_tag general_page.haylage_home_banner_url(:thumbnail).to_s %></td>
        <td>
          <%= link_to 'Show', general_page %><br />
          <%= link_to 'Edit', edit_general_page_path(general_page) %>
          <%#= link_to 'Destroy', general_page, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/general_pages/new.html.erb
<div class="heading heading-desktop heading-admin">
	New 
</div>

<%= render 'form' %>

app/views/general_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_general_page_path(@general_page) %> |
<%= link_to 'Back', general_pages_path %>