config/routes.rb
RobinsonFarms::Application.routes.draw do

  devise_for :users
  get 'general_pages/admin' => 'general_pages#admin', as: :admin
  get 'subcategories/show_all' => 'subcategories#show_all', as: :show_all

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :list_items
  end

  resources :general_pages

  resources :list_items

   root 'general_pages#home'

end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
	belongs_to :subcategory

	mount_uploader :item_image, ImageUploader
	mount_uploader :home_page_image, ImageUploader
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show]

  # GET /list_items
  # GET /list_items.json
  def index
    @subcategories = Subcategory.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:name, :description, :item_image, :optional_information, :link_text, :subcategory_id,
        :home_page_image)
    end
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= render 'layouts/admin_menu' %>

<%= form_for(@list_item) do |f| %>
  <% if @list_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
      <% @list_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% f.hidden_field('subcategory_id', :value => params[:subcategory_id]) %>

  <div class="admin-form-heading">
    <p>Choose Subcategory</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :subcategory_id %>
    </div>
    <div class="col span-input admin-field">
      <%= f.collection_select :subcategory_id, Subcategory.order(:name), :id, :name, :include_blank=>true %>
    </div>
  </div>

  <div class="admin-form-heading">
    <p>Details</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :name, "Name/Title" %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :name %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :link_text, 'Link Text (optional)' %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_field :link_text %>
    </div>
  </div> 

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :description %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :description, :class => 'tinymce', :rows => 10, :cols => 60 %>
      <%= tinymce %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :optional_information %>
    </div>
    <div class="col span-input admin-field">
      <%= f.text_area :optional_information, :class => 'tinymce', :rows => 10, :cols => 60 %>
      <%= tinymce %>

    </div>
  </div>     

  <div class="admin-form-heading">
    <p>Image(s)</p>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :item_image, 'Image' %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :item_image %>
    </div>
  </div>

  <div class="section group">
    <div class="col span-label admin-label">
      <%= f.label :home_page_image, "Homepage Image (optional)" %>
    </div>
    <div class="col span-input admin-field">
      <%= f.file_field :home_page_image %>
    </div>
  </div>


  <div class="actions">
    <%= f.submit "Save", :class => "button button-new" %>
  </div>
<% end %>

app/views/list_items/edit.html.erb
<div class="heading heading-desktop heading-admin">
	Edit
</h1>

<%= render 'form' %>

app/views/list_items/index.html.erb
<%= render 'layouts/admin_menu' %>

<div class="heading heading-desktop heading-admin">
  Subcategory Content
</div>

<% @subcategories.each do |subcategory| %>
  <% @list_items = ListItem.where(:subcategory_id => subcategory.id) %> 
  <div class="admin-section-heading">
    <%= subcategory.name %>
  </div>

  <table class="admin-table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Subcategory</th>
        <th>Description</th>
        <th>Image</th>
        <th>Home Page Image</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @list_items.each do |list_item| %>
        <tr>
          <td><%= list_item.name %></td>
          <td><%= list_item.subcategory.name %></td>
          <td><%= list_item.description.html_safe unless list_item.description.nil? %></td>
          <td><%= image_tag list_item.item_image_url(:thumbnail).to_s %></td>
          <td><%= image_tag list_item.home_page_image_url(:thumbnail).to_s %></td>
          <td>
            <%= link_to 'Show', list_item %><br />
            <%= link_to 'Edit', edit_list_item_path(list_item) %><br />
            <%= link_to 'Destroy', list_item, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table> 

  <%= link_to 'Create Content', new_list_item_path, :class => "button button-new" %> 

<% end %>

app/views/list_items/new.html.erb
<div class="heading heading-desktop heading-admin">
	New 
</div>

<%= render 'form' %>

app/views/list_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_list_item_path(@list_item) %> |
<%= link_to 'Back', list_items_path %>