config/routes.rb
RobinsonFarms::Application.routes.draw do

  devise_for :users
  get 'general_pages/admin' => 'general_pages#admin', as: :admin
  get 'subcategories/show_all' => 'subcategories#show_all', as: :show_all

  resources :categories do
    resources :subcategories
  end

  resources :subcategories do
    resources :list_items
  end

  resources :general_pages

  resources :list_items

   root 'general_pages#home'

end

app/views/layouts/_admin_menu.html.erb
<div class="section group">
	<nav id="admin-wrap">
		<ul id="admin-menu">
			<li><%= link_to "Back to Site", root_url %></li>
			<li><%= link_to "General Settings", general_pages_url %></li>
			<li><%= link_to "Categories", categories_url %></li>
			<li><%= link_to "Subcategories", subcategories_url %></li>
			<li><%= link_to "Subcategories Content", list_items_url %></li>
		</ul>
	</nav>	
</div>

app/views/layouts/_menu_desktop.html.erb
<div class="section">
	<div class="menu col span-1-of-3 section-on-top">
		<div class="col-full-row">
			<% general_page = GeneralPage.first %>
			<%= image_tag general_page.menu_image_url.to_s %>
			<ul class="menu-list-phone">
				<li><%= image_tag general_page.phone_image %><%= general_page.phone_number %></li>
			</ul>
			<ul class="menu-list-links">
				<li><%= link_to "Home", root_url %></li>
				<% about = Category.where(:name=>"About Us").first %>
				<li><%= link_to "About Us", category_path(about) %></li>
				<% meet = Subcategory.where(:name=>"Meet The Robinsons").first %>
				<li><%= link_to "The Robinsons", subcategory_path(meet) %></li>
				<li><%= link_to "Our Products", root_url(:anchor => "products") %></li>
				<% client = Subcategory.where(:name=>"Our Clients").first %>
				<li><%= link_to "Our Clients", subcategory_path(client) %></li>
				<li><%= link_to "Contact Us", :anchor => "map" %></li>
				<% if user_signed_in? %>
				<li><%= link_to "Admin Area", admin_path %></li>
				<% end %>				
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_menu_mobile.html.erb
<nav id="nav-wrap">

	<ul id="nav">
		<li><%= link_to "Home", root_url %></li>
		<% about = Category.where(:name=>"About Us").first %>
		<li><%= link_to "About Us", category_path(about) %></li>
		<% meet = Subcategory.where(:name=>"Meet The Robinsons").first %>
		<li><%= link_to "The Robinsons", subcategory_path(meet) %></li>
		<li><%= link_to "Our Products", root_url(:anchor => "products") %></li>
		<% client = Subcategory.where(:name=>"Our Clients").first %>
		<li><%= link_to "Our Clients", subcategory_path(client) %></li>
		<li><%= link_to "Contact Us", :anchor => "map" %></li>
	</ul>

</nav>

app/views/layouts/_social_feed_top.html.erb
<div class="section group social-feed-top">
	<div class="col span-5-of-5 like-box-frame">
		<h4>TOP NEWS</h4>
		Robinson Farms <div class="fb-like" data-href="https://www.facebook.com/robinson.farms.3" data-width="60px" data-layout="button_count" data-action="like" data-show-faces="false" data-share="false"></div>
        <%= image_tag("fb-image-01.png") %>
        <%= image_tag("fb-image-02.png") %>		
	</div>
	<div class="col span-4-of-5 social-media-image">
		<%= link_to image_tag("facebook.png"), 'https://www.facebook.com/RobinsonFarms.ie?fref=ts',:target => "something_unique" %>
	</div>
	<div class="col span-3-of-5 social-media-image">
		<%= link_to image_tag("twitter.png"), 'https://twitter.com/RobinsonFarms', :tarbeg => "something_unique" %>
	</div>
	<div class="col span-2-of-5 social-media-image ">
		<%= link_to image_tag("youtube.png"), 'https://www.youtube.com/channel/UCHC4dL8-8TTdhI892Aj25UQ', :target => "soomething_unique" %>
	</div>
	<div class="col span-1-of-5 social-media-image">
		<%= link_to image_tag("instagram.png")%>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RobinsonFarms</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<div class="page-body">
		<!-- this div is needed for the facebook like button to work -->
		<div id="fb-root"></div>
		<%= yield %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>		
	</div>

	<!-- fb like button script - for some reason this is not being read when placed in application.js -->
	<script>(function(d, s, id) {
	  var js, fjs = d.getElementsByTagName(s)[0];
	  if (d.getElementById(id)) return;
	  js = d.createElement(s); js.id = id;
	  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
	  fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>	

	<!-- script for mobiole menu not working in application.js -->
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>

	<script type="text/javascript">
	jQuery(document).ready(function($){

		/* prepend menu icon */
		$('#nav-wrap').prepend('<div id="menu-icon">Menu</div>');
		
		/* toggle nav */
		$("#menu-icon").on("click", function(){
			$("#nav").slideToggle();
			$(this).toggleClass("active");
		});

	});
	</script>

</body>
</html>